// app/api/ai/generate/route.ts — AI แปลง prompt → component config OR fallback to chat

import { NextRequest, NextResponse } from "next/server";

const GEMINI_MODEL = "gemini-2.5-flash";
const GEMINI_URL = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`;

const CONFIG_PROMPT = `You are a CI/CD pipeline configuration assistant for PipeGen.

Your job: convert a user's natural language request into a JSON config object.

Available config fields (set to true to enable, false or omit to disable):

LANGUAGES:
- use_node: boolean — Enable Node.js
- use_python: boolean — Enable Python
- use_go: boolean — Enable Go
- use_rust: boolean — Enable Rust

TRIGGERS:
- enable_push: boolean — Trigger on push
- enable_pr: boolean — Trigger on pull request

QUALITY:
- run_tests: boolean — Run automated tests
- check_quality: boolean — Run linter
- enable_security: boolean — Run security scanning
- enable_coverage: boolean — Upload test coverage

BUILD & DEPLOY:
- run_build: boolean — Build the project
- docker_build: boolean — Build Docker image
- deploy_vercel: boolean — Deploy to Vercel

NOTIFICATIONS:
- enable_slack: boolean — Send Slack notification

RULES:
1. Return ONLY valid JSON. No markdown, no backticks, no explanation.
2. Only include fields the user mentions or implies.
3. If user says "full pipeline" or "complete", enable: use_node, enable_push, enable_pr, run_tests, check_quality, run_build.
4. We only support Node.js, Python, Go, Rust. If user asks for unsupported language return: {"error":"fallback_to_chat"}

Example: "Node.js pipeline with testing and docker"
Output: {"use_node":true,"enable_push":true,"enable_pr":true,"run_tests":true,"run_build":true,"docker_build":true}`;

export async function POST(request: NextRequest) {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return NextResponse.json({ error: "AI not configured" }, { status: 501 });
  }

  // อ่าน body ครั้งเดียว
  let body: { prompt: string };
  try {
    body = (await request.json()) as { prompt: string };
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const prompt = body.prompt?.trim();
  if (!prompt) {
    return NextResponse.json({ error: "Prompt is required" }, { status: 400 });
  }

  try {
    // Step 1: AI แปลง prompt → config
    const res = await fetch(`${GEMINI_URL}?key=${encodeURIComponent(apiKey)}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        systemInstruction: { parts: [{ text: CONFIG_PROMPT }] },
        contents: [{ role: "user", parts: [{ text: prompt }] }],
        generationConfig: { maxOutputTokens: 1024, temperature: 0.1 },
      }),
    });

    const data = await res.json().catch(() => ({}));
    if (!res.ok) {
      return NextResponse.json({ error: data?.error?.message || "AI request failed" }, { status: 502 });
    }

    const text = data?.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || "";
    const clean = text.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
    const config = JSON.parse(clean);

    // เช็คว่า AI บอก fallback หรือไม่มีภาษาที่รองรับ
    const hasSupported = config.use_node || config.use_python || config.use_go || config.use_rust;
    if (config.error === "fallback_to_chat" || !hasSupported) {
      // Step 2: Fallback → AI gen YAML ตรงๆ ที่ server
      const chatRes = await fetch(`${GEMINI_URL}?key=${encodeURIComponent(apiKey)}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          systemInstruction: { parts: [{ text: "You are a CI/CD pipeline assistant. Generate a valid GitHub Actions or GitLab CI YAML for the user's request. Output a brief explanation followed by the YAML in a code block." }] },
          contents: [{ role: "user", parts: [{ text: prompt }] }],
          generationConfig: { maxOutputTokens: 4096, temperature: 0.3 },
        }),
      });

      const chatData = await chatRes.json().catch(() => ({}));
      const chatText = chatData?.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || "";

      return NextResponse.json({
        config: null,
        fallback: true,
        content: chatText + "\n\n⚠️ *This language doesn't have built-in templates, so the YAML was generated by AI. Please review before using.*",
      });
    }

    return NextResponse.json({ config, fallback: false });
  } catch (e) {
    console.error("[ai/generate]", e);
    return NextResponse.json(
      { error: e instanceof Error ? e.message : "Failed to parse AI response" },
      { status: 502 },
    );
  }
}