import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../packages/components/layout/Navbar";
import Providers from "./providers";
import { PipelineProvider } from "../packages/components/workspace/PipelineProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pipe Gen",
  description: "Generated by create next app",
  icons: {
    icon: "logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Providers>
          <div className="flex flex-1 flex-col min-h-0 overflow-hidden">
            <div className="shrink-0">
              <Navbar />
            </div>
            <div className="flex-1 min-h-0 overflow-hidden flex flex-col">
              <PipelineProvider>{children}</PipelineProvider>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
