import type { ComponentCategory, ComponentValues } from "../../packages/types/pipeline";
export const baseValues: ComponentValues = { pipeline_name: "Test-Pipeline", runner_os: "ubuntu-latest", checkout_ver: "v4" };
export const MOCK_CATEGORIES: ComponentCategory[] = [
  { id: "cat-general", name: "1. General Settings", slug: "general", displayOrder: 1, icon: "Settings", components: [
    { id: "comp-info", categoryId: "cat-general", name: "Project Info", type: "group", uiConfig: { fields: [{ id: "pipeline_name", type: "input", defaultValue: "My-Pipeline" }] }, syntaxes: [{ platform: "github", template: "name: {{pipeline_name}}\n" }, { platform: "gitlab", template: "# Pipeline: {{pipeline_name}}\n" }] },
    { id: "comp-triggers", categoryId: "cat-general", name: "When to Run? (Triggers)", type: "group", uiConfig: { fields: [
      { id: "enable_push", type: "switch", defaultValue: false }, { id: "push_branches", type: "branch_select", visibleIf: { fieldId: "enable_push", value: true }, templates: { github: "  push:\n    branches: {{value}}", gitlab: "    - if: $CI_COMMIT_BRANCH == {{value}}" } } as any,
      { id: "enable_pr", type: "switch", defaultValue: false }, { id: "pr_branches", type: "branch_select", visibleIf: { fieldId: "enable_pr", value: true }, templates: { github: "  pull_request:\n    branches: {{value}}", gitlab: '    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == {{value}}' } } as any,
      { id: "enable_schedule", type: "switch", defaultValue: false }, { id: "cron_expression", type: "input", defaultValue: "0 * * * *", visibleIf: { fieldId: "enable_schedule", value: true } } as any,
    ] }, syntaxes: [
      { platform: "github", template: "on:\n{{FIELDS}}\n\njobs:\n  build-and-deploy:\n    runs-on: {{runner_os}}\n    steps:\n      - name: Checkout Code\n        uses: actions/checkout@{{checkout_ver}}" },
      { platform: "gitlab", template: "workflow:\n  rules:\n{{FIELDS}}\n\n{{DEFAULT_BLOCK}}cache:\n  key: \"$CI_COMMIT_REF_SLUG\"\n  paths:\n    - node_modules/\n  policy: pull-push\n\nstages:\n  - setup\n  - test\n  - build\n  - deploy\n" },
    ] },
    { id: "comp-include", categoryId: "cat-general", name: "Include Pipeline Files", type: "group", uiConfig: { fields: [{ id: "use_include", type: "switch", defaultValue: false }, { id: "include_paths", type: "file_multi_select", visibleIf: { fieldId: "use_include", value: true } } as any] }, syntaxes: [{ platform: "gitlab", template: "include:{{include_paths}}" }] },
    { id: "comp-system", categoryId: "cat-general", name: "System & Runner (Advanced)", type: "group", uiConfig: { fields: [{ id: "runner_os", type: "select", defaultValue: "ubuntu-latest", options: [{ value: "ubuntu-latest" }, { value: "macos-13" }, { value: "windows-latest" }] }, { id: "checkout_ver", type: "select", defaultValue: "v4", options: [{ value: "v4" }, { value: "v3" }] }] }, syntaxes: [] },
  ] },
  { id: "cat-runtime", name: "2. Language & Tools", slug: "runtime", displayOrder: 2, icon: "Server", components: [
    { id: "comp-node", categoryId: "cat-runtime", name: "Node.js / JavaScript", type: "group", uiConfig: { fields: [
      { id: "use_node", type: "switch", defaultValue: false },
      { id: "node_version", type: "select", defaultValue: "18", visibleIf: { fieldId: "use_node", value: true }, options: [{ value: "20" }, { value: "18" }, { value: "16" }] } as any,
      { id: "pkg_manager", type: "select", defaultValue: "npm", visibleIf: { fieldId: "use_node", value: true }, options: [{ value: "npm" }, { value: "yarn" }, { value: "pnpm" }, { value: "bun" }], linkedFields: { install_cmd: { npm: "npm ci", yarn: "yarn install --frozen-lockfile", pnpm: "pnpm install --frozen-lockfile", bun: "bun install --frozen-lockfile" }, test_cmd: { npm: "npm test", yarn: "yarn test", pnpm: "pnpm test", bun: "bun test" }, build_cmd: { npm: "npm run build", yarn: "yarn build", pnpm: "pnpm run build", bun: "bun run build" }, lint_cmd: { npm: "npm run lint", yarn: "yarn lint", pnpm: "pnpm run lint", bun: "bun run lint" } } } as any,
      { id: "install_cmd", type: "select", defaultValue: "npm ci", visibleIf: { fieldId: "use_node", value: true }, options: [{ value: "npm ci" }, { value: "yarn install --frozen-lockfile" }, { value: "pnpm install --frozen-lockfile" }, { value: "bun install --frozen-lockfile" }] } as any,
    ] }, syntaxes: [
      { platform: "github", template: "      - name: Setup Node.js\n        uses: actions/setup-node@v4\n        with:\n          node-version: '{{node_version}}'\n      - name: Install Dependencies\n        run: |\n          if ! command -v {{pkg_manager}} > /dev/null 2>&1; then npm install -g {{pkg_manager}}; fi\n          {{install_cmd}}" },
      { platform: "gitlab", template: "setup_node:\n  stage: setup\n  image: node:{{node_version}}\n  script:\n    - {{install_cmd}}" },
    ] },
    { id: "comp-python", categoryId: "cat-runtime", name: "Python", type: "group", uiConfig: { fields: [{ id: "use_python", type: "switch", defaultValue: false, linkedFields: { test_cmd: { "true": "pytest" }, lint_cmd: { "true": "flake8" }, build_cmd: { "true": "python -m build" } } } as any, { id: "py_version", type: "select", defaultValue: "3.9", visibleIf: { fieldId: "use_python", value: true }, options: [{ value: "3.9" }, { value: "3.10" }, { value: "3.11" }] } as any] }, syntaxes: [{ platform: "github", template: "      - name: Setup Python\n        uses: actions/setup-python@v4\n        with:\n          python-version: '{{py_version}}'\n      - name: Install Python Dependencies\n        run: pip install -r requirements.txt" }, { platform: "gitlab", template: "setup_python:\n  stage: setup\n  image: python:{{py_version}}\n  before_script: []\n  script:\n    - pip install -r requirements.txt" }] },
    { id: "comp-go", categoryId: "cat-runtime", name: "Go", type: "group", uiConfig: { fields: [{ id: "use_go", type: "switch", defaultValue: false, linkedFields: { test_cmd: { "true": "go test -v ./..." }, build_cmd: { "true": "go build -v ./..." } } } as any, { id: "go_version", type: "select", defaultValue: "1.21", visibleIf: { fieldId: "use_go", value: true }, options: [{ value: "1.22" }, { value: "1.21" }] } as any] }, syntaxes: [{ platform: "github", template: "      - name: Setup Go\n        uses: actions/setup-go@v5\n        with:\n          go-version: '{{go_version}}'" }, { platform: "gitlab", template: "setup_go:\n  stage: setup\n  image: golang:{{go_version}}\n  before_script: []\n  script:\n    - echo \"Go ready\"" }] },
    { id: "comp-rust", categoryId: "cat-runtime", name: "Rust", type: "group", uiConfig: { fields: [{ id: "use_rust", type: "switch", defaultValue: false, linkedFields: { test_cmd: { "true": "cargo test" }, build_cmd: { "true": "cargo build --release" } } } as any, { id: "rust_version", type: "select", defaultValue: "stable", visibleIf: { fieldId: "use_rust", value: true }, options: [{ value: "stable" }, { value: "1.75" }] } as any] }, syntaxes: [{ platform: "github", template: "      - name: Setup Rust\n        uses: dtolnay/rust-toolchain@stable\n        with:\n          toolchain: {{rust_version}}" }, { platform: "gitlab", template: "setup_rust:\n  stage: setup\n  image: rust:{{rust_version}}\n  before_script: []\n  script:\n    - echo \"Rust ready\"" }] },
    { id: "comp-cache", categoryId: "cat-runtime", name: "Dependency Cache", type: "group", uiConfig: { fields: [{ id: "enable_cache", type: "switch", defaultValue: false }, { id: "cache_path", type: "input", defaultValue: "node_modules", visibleIf: { fieldId: "enable_cache", value: true } } as any, { id: "cache_key", type: "input", defaultValue: "npm-${{ runner.os }}", visibleIf: { fieldId: "enable_cache", value: true } } as any] }, syntaxes: [{ platform: "github", template: "      - name: Cache dependencies\n        uses: actions/cache@v4\n        with:\n          path: {{cache_path}}\n          key: {{cache_key}}" }, { platform: "gitlab", template: "" }] },
  ] },
  { id: "cat-quality", name: "3. Quality Checks", slug: "quality", displayOrder: 3, icon: "ShieldCheck", components: [
    { id: "comp-test", categoryId: "cat-quality", name: "Testing Strategy", type: "group", uiConfig: { fields: [{ id: "run_tests", type: "switch", defaultValue: false }, { id: "test_cmd", type: "select", defaultValue: "npm test", visibleIf: { fieldId: "run_tests", value: true }, options: [{ value: "npm test" }, { value: "yarn test" }, { value: "pytest" }, { value: "go test -v ./..." }, { value: "cargo test" }] } as any] }, syntaxes: [{ platform: "github", template: "      - name: Run Tests\n        run: {{test_cmd}}" }, { platform: "gitlab", template: "test_job:\n  stage: test\n  script:\n    - {{runtime_install}}\n    - {{test_cmd}}" }] },
    { id: "comp-lint", categoryId: "cat-quality", name: "Code Quality (Lint)", type: "group", uiConfig: { fields: [{ id: "check_quality", type: "switch", defaultValue: false }, { id: "lint_cmd", type: "select", defaultValue: "npm run lint", visibleIf: { fieldId: "check_quality", value: true }, options: [{ value: "npm run lint" }, { value: "yarn lint" }, { value: "flake8" }, { value: "golangci-lint run" }] } as any] }, syntaxes: [{ platform: "github", template: "      - name: Check Code Quality\n        run: {{lint_cmd}}" }, { platform: "gitlab", template: "lint_job:\n  stage: test\n  script:\n    - {{runtime_install}}\n    - {{lint_cmd}}" }] },
    { id: "comp-security", categoryId: "cat-quality", name: "Security (SAST / audit)", type: "group", uiConfig: { fields: [{ id: "enable_security", type: "switch", defaultValue: false }, { id: "security_tool", type: "select", defaultValue: "npm_audit", visibleIf: { fieldId: "enable_security", value: true }, options: [{ value: "npm_audit" }, { value: "trivy" }, { value: "codeql" }] } as any] }, syntaxes: [{ platform: "github", template: "      - name: Security check\n        run: |\n          case \"{{security_tool}}\" in\n            npm_audit) npm audit --audit-level=high ;;\n            trivy) docker run --rm aquasec/trivy fs /src ;;\n            *) npm audit --audit-level=high ;;\n          esac" }, { platform: "gitlab", template: "security_job:\n  stage: test\n  script:\n    - npm audit --audit-level=high" }] },
    { id: "comp-coverage", categoryId: "cat-quality", name: "Coverage report", type: "group", uiConfig: { fields: [{ id: "enable_coverage", type: "switch", defaultValue: false }, { id: "coverage_provider", type: "select", defaultValue: "codecov/codecov-action@v4", visibleIf: { fieldId: "enable_coverage", value: true }, options: [{ value: "codecov/codecov-action@v4" }, { value: "coverallsapp/github-action@v2" }] } as any, { id: "coverage_token_secret", type: "input", defaultValue: "CODECOV_TOKEN", visibleIf: { fieldId: "enable_coverage", value: true } } as any] }, syntaxes: [{ platform: "github", template: "      - name: Upload Coverage\n        uses: {{coverage_provider}}\n        with:\n          token: ${{ secrets.{{coverage_token_secret}} }}" }, { platform: "gitlab", template: "coverage_job:\n  stage: test\n  script:\n    - {{coverage_test_cmd}}" }] },
  ] },
  { id: "cat-build", name: "4. Build & Delivery", slug: "build", displayOrder: 4, icon: "Box", components: [
    { id: "comp-build", categoryId: "cat-build", name: "Build Application", type: "group", uiConfig: { fields: [{ id: "run_build", type: "switch", defaultValue: false }, { id: "build_cmd", type: "select", defaultValue: "npm run build", visibleIf: { fieldId: "run_build", value: true }, options: [{ value: "npm run build" }, { value: "yarn build" }, { value: "go build -v ./..." }, { value: "cargo build --release" }] } as any] }, syntaxes: [{ platform: "github", template: "      - name: Build Project\n        run: {{build_cmd}}" }, { platform: "gitlab", template: "build_job:\n  stage: build\n  script:\n    - {{runtime_install}}\n    - {{build_cmd}}\n  artifacts:\n    paths:\n      - dist/" }] },
    { id: "comp-docker", categoryId: "cat-build", name: "Docker Containerization", type: "group", uiConfig: { fields: [{ id: "docker_build", type: "switch", defaultValue: false }, { id: "image_name", type: "input", defaultValue: "username/repo", visibleIf: { fieldId: "docker_build", value: true } } as any, { id: "docker_tag", type: "select", defaultValue: "latest", visibleIf: { fieldId: "docker_build", value: true }, options: [{ value: "latest" }] } as any, { id: "docker_push", type: "switch", defaultValue: false, visibleIf: { fieldId: "docker_build", value: true } } as any] }, syntaxes: [{ platform: "github", template: "      - name: Build Docker Image\n        run: docker build -t {{image_name}}:{{docker_tag}} .\n      - name: Push to Docker Hub\n        if: {{docker_push}}\n        run: docker push {{image_name}}:{{docker_tag}}" }, { platform: "gitlab", template: "docker_job:\n  stage: deploy\n  image: docker:latest\n  services:\n    - docker:dind\n  script:\n    - docker build -t {{image_name}}:{{docker_tag}} ." }] },
    { id: "comp-vercel", categoryId: "cat-build", name: "Deploy to Vercel", type: "group", uiConfig: { fields: [{ id: "deploy_vercel", type: "switch", defaultValue: false }] }, syntaxes: [{ platform: "github", template: "      - name: Deploy to Vercel\n        run: |\n          npm i -g vercel\n          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}" }, { platform: "gitlab", template: "deploy_vercel:\n  stage: deploy\n  image: node:20\n  script:\n    - npm i -g vercel\n    - vercel deploy --prod --token=$VERCEL_TOKEN" }] },
  ] },
  { id: "cat-notifications", name: "5. Notifications", slug: "notifications", displayOrder: 5, icon: "Bell", components: [
    { id: "comp-slack", categoryId: "cat-notifications", name: "Slack Notification", type: "group", uiConfig: { fields: [{ id: "enable_slack", type: "switch", defaultValue: false }, { id: "slack_notify_on", type: "select", defaultValue: "always", visibleIf: { fieldId: "enable_slack", value: true }, options: [{ value: "on_failure" }, { value: "on_success" }, { value: "always" }], linkedFields: { slack_github_condition: { on_failure: "failure()", on_success: "success()", always: "always()" }, slack_github_status: { on_failure: "failed", on_success: "passed", always: "completed" }, slack_gitlab_when: { on_failure: "on_failure", on_success: "on_success", always: "always" }, slack_gitlab_status: { on_failure: "failed", on_success: "passed", always: "completed" } } } as any] }, syntaxes: [{ platform: "github", template: "      - name: Notify Slack\n        if: {{slack_github_condition}}\n        run: |\n          curl -X POST --data '{\"text\":\"pipeline {{slack_github_status}}\"}' ${{ secrets.SLACK_WEBHOOK_URL }}" }, { platform: "gitlab", template: "notify_slack:\n  stage: .post\n  image: curlimages/curl:latest\n  script:\n    - curl -X POST --data '{\"text\":\"pipeline {{slack_gitlab_status}}\"}' \"$SLACK_WEBHOOK_URL\"\n  rules:\n    - when: {{slack_gitlab_when}}" }] },
  ] },
];
